// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://nmtwtppvobftqwfeuwpl.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im5tdHd0cHB2b2JmdHF3ZmV1d3BsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTM4Mjk0MTQsImV4cCI6MjA2OTQwNTQxNH0.VxM1uBqJM6tpskAeB8BaIP4I7ixzVa7oiU7JAowqHt8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});